"use client";
import type { TActivationMetrics } from "@/lib/onboarding/activation-metrics";
const minutes = (value: number | null) => value === null ? "Ainda sem conclusão" : `${Math.round(Number(value))} min`;
export default function OnboardingMetricsPage({ metrics }: { metrics: TActivationMetrics }) {
 return <main className="flex flex-col gap-8 p-6">
  <div><h1 className="text-2xl font-bold">Ativação de organizações</h1><p className="max-w-prose text-sm text-muted-foreground">Configuração e importação medidas pelos registros persistidos. Uma prévia concluída não representa venda ou retorno financeiro.</p></div>
  <section><h2 className="mb-3 text-lg font-bold">Jornadas</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Produto</th><th className="p-2">Iniciadas</th><th className="p-2">Concluídas</th><th className="p-2">Tempo médio</th></tr></thead><tbody>{metrics.journeys.map((row) => <tr className="border-t border-border" key={row.produto}><td className="p-2">{row.produto}</td><td className="p-2">{row.total}</td><td className="p-2">{row.concluidas} ({Math.round(row.concluidas / row.total * 100)}%)</td><td className="p-2">{minutes(row.tempoMedioMinutos)}</td></tr>)}</tbody></table></div></section>
  <section><h2 className="mb-3 text-lg font-bold">Carga histórica por provedor</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Provedor", "Estado", "Cargas", "Vendas", "Requisições/venda", "Limites", "Tempo médio"].map((label) => <th className="p-2" key={label}>{label}</th>)}</tr></thead><tbody>{metrics.imports.map((row) => <tr className="border-t border-border" key={`${row.provedor}-${row.estado}`}><td className="p-2">{row.provedor}</td><td className="p-2">{row.estado.replaceAll("_", " ").toLocaleLowerCase("pt-BR")}</td><td className="p-2">{row.total}</td><td className="p-2">{row.vendasImportadas}</td><td className="p-2">{Number(row.vendasImportadas) > 0 ? (Number(row.requisicoes) / Number(row.vendasImportadas)).toFixed(2) : "—"}</td><td className="p-2">{row.limites}</td><td className="p-2">{minutes(row.tempoMedioMinutos)}</td></tr>)}</tbody></table></div></section>
  <section><h2 className="mb-3 text-lg font-bold">Campanhas e canais</h2><ul className="flex flex-col gap-2 text-sm">{metrics.campaigns.map((row) => <li key={String(row.ativo)}>{row.total} campanhas {row.ativo ? "ativas" : "preparadas ou aguardando dependências"}</li>)}{metrics.channels.map((row) => <li key={row.canal ?? "nenhum"}>{row.canal ?? "Canal não escolhido"}: {row.total} jornadas, {row.simulacoes} prévias concluídas</li>)}</ul></section>
  <section><h2 className="mb-3 text-lg font-bold">Etapas e adiamentos</h2><ul className="flex flex-col divide-y divide-border text-sm">{metrics.stages.map((row) => <li className="py-2" key={`${row.produto}-${row.etapa}-${row.segmento}`}>{row.produto} · {row.segmento ?? "Sem segmento"} · {row.etapa}: {row.total} jornadas, {row.adiamentos} etapas adiadas</li>)}</ul></section>
  {!metrics.journeys.length ? <p className="text-sm text-muted-foreground">Nenhuma jornada registrada neste ambiente.</p> : null}
 </main>;
}
