import {
	PLATFORM_PARTNER_COOKIE_MAX_AGE_SECONDS,
	PLATFORM_PARTNER_MONTHLY_FIRST_INVOICE_BPS,
	PLATFORM_PARTNER_MONTHLY_SUBSEQUENT_INVOICE_BPS,
	PLATFORM_PARTNER_MONTHLY_THIRD_INVOICE_BPS,
	PLATFORM_PARTNER_YEARLY_INVOICE_BPS,
} from "@/lib/platform-partnerships/constants";

const bpsToPercent = (bps: number) => bps / 100;

/** Mensalidade do plano Plataforma: base comissionável. Consultoria não entra. */
export const COMMISSIONABLE_MONTHLY_BASE = 399.9;

export const FIRST_INVOICE_PERCENT = bpsToPercent(PLATFORM_PARTNER_MONTHLY_FIRST_INVOICE_BPS); // 100
export const THIRD_INVOICE_PERCENT = bpsToPercent(PLATFORM_PARTNER_MONTHLY_THIRD_INVOICE_BPS); // 100
export const SUBSEQUENT_INVOICE_PERCENT = bpsToPercent(PLATFORM_PARTNER_MONTHLY_SUBSEQUENT_INVOICE_BPS); // 20
export const YEARLY_INVOICE_PERCENT = bpsToPercent(PLATFORM_PARTNER_YEARLY_INVOICE_BPS); // 27

export const ATTRIBUTION_DAYS = Math.round(PLATFORM_PARTNER_COOKIE_MAX_AGE_SECONDS / (60 * 60 * 24)); // 30

export const FIRST_MONTH_PAYOUT = COMMISSIONABLE_MONTHLY_BASE * (FIRST_INVOICE_PERCENT / 100);
export const THIRD_MONTH_PAYOUT = COMMISSIONABLE_MONTHLY_BASE * (THIRD_INVOICE_PERCENT / 100);
export const RECURRING_MONTH_PAYOUT = COMMISSIONABLE_MONTHLY_BASE * (SUBSEQUENT_INVOICE_PERCENT / 100);
export const FIRST_YEAR_PAYOUT = FIRST_MONTH_PAYOUT + THIRD_MONTH_PAYOUT + RECURRING_MONTH_PAYOUT * 10;

export const PARTNER_LOGIN_HREF = "/auth/signin?redirectTo=%2Fpartner-dashboard";
export const PROGRAM_PAGE_HREF = "/programa-de-parceiros";
